# To use:
#
#   $ micromamba create -f environment.yml  # `micromamba` works too for this command
#   $ micromamba activate cuh2vizR_dev
#
name: cuh2vizR_dev
channels:
  - conda-forge
dependencies:
  - compilers
  - meson
  - ninja
  - cmake
  - pkg-config
  # Backports away from C++20
  - range-v3
  - fmt==9.1.0
  # Tests
  - gtest
  # Potlib dep
  - openblas
  - gfortran
  # (pinned)
  - eigen==3.4.0
  # (libs)
  - fmt
  - spdlog
  # R bindings
  # (core)
  - r-devtools
  - r-roxygen2
  - r-cpp11
  # (test)
  - r-testthat
  - r-assertthat
  # (cli)
  - r-optparse
  - r-cli
  # (lint)
  - r-styler
  - r-lintr
  # (animation)
  - r-gifski
  - ffmpeg
  # (extra)
  - r-microbenchmark
  - r-foreach
  - r-doParallel
  # Interactivity
  - radian
  - r-irkernel
  - jupyter
  - r-rmarkdown
