[project]
name = "cuh2vizR"
version = "0.1.0"
description = "Add a short description here"
authors = ["Rohit Goswami <rog32@hi.is>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
r-renv = "1.0.2.*"
compilers = "1.6.0.*"
pkg-config = "0.29.2.*"
gtest = "1.14.0.*"
eigen = "==3.4.0"
ninja = "1.11.1.*"
range-v3 = "0.12.0.*"
fmt = "10.1.0.*"
meson = "1.2.1.*"
cmake = "3.26.4.*"
gfortran = "12.3.0.*"
spdlog = "1.12.0.*"
openblas = "0.3.23.*"
radian = "0.6.7.*"
