on:
  push:
    branches: [main, master, v2-branch]
  pull_request:
    branches: [main, master, v2-branch]

name: ROpenSci-pkgcheck
    runs-on: ubuntu-latest
    steps:
      - name: pkgcheck
        uses: ropensci-review-tools/pkgcheck-action@v1.0.0
